
version: 2

models:
  - name: bids_bronze
    description: "Bronze table for bids data"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: bids_device_silver
    description: "Silver table for devices"
    columns:
      - name: device_auction_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
